import type { PublicLocale } from "@/i18n/locales";
import type { LocalizedArticleContent } from "@/content/localized/types";

export const localizedSafetyToolsArticles: Record<PublicLocale, LocalizedArticleContent> = {
  de: {
    locale: "de",
    slug: "lokale-sicherheitswerkzeuge-qr-email-links",
    metaTitle: "Lokale Tools für QR Codes, E Mail Header und sichere Links",
    metaDescription: "Praxisleitfaden zu 20 lokalen Browser Tools für QR Codes, E Mail Header, Zahlungsanfragen, Weiterleitungen und digitale Sicherheit.",
    title: "QR Codes, E Mail Header und Links prüfen, bevor eine kleine Unsicherheit zum Problem wird",
    excerpt: "20 lokale Browser Tools helfen dabei, digitale Signale zu ordnen, ohne Links automatisch zu öffnen oder Eingaben an einen Server zu senden.",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "Navines Team",
    sections: [
      { title: "Warum eine kurze Prüfung sinnvoll ist", paragraphs: ["Viele Vorfälle beginnen mit einem scheinbar kleinen Detail: einem QR Code auf einem Ausdruck, einer geänderten Antwortadresse oder einer dringenden Zahlungsanfrage. Ein lokales Werkzeug kann diese Signale sichtbar machen und den nächsten Prüfschritt strukturieren.", "Die Ergebnisse sind Hinweise und keine Sicherheitsgarantie. Sensible Entscheidungen sollten zusätzlich über eine bekannte offizielle Quelle bestätigt werden."] },
      { title: "QR Code aus einem Bild lesen", paragraphs: ["Der QR Scanner liest den Code im Browser, zeigt die Zieladresse an und öffnet sie nicht automatisch. So lässt sich die Domain prüfen, bevor das Gerät zum Ziel wechselt.", "Für gedruckte Kampagnen ergänzt eine Checkliste die technische Prüfung um Mobilansicht, HTTPS, Ersatzadresse, Kontrast und einen Test mit einem realen Ausdruck."] },
      { title: "E Mail Header und Zahlungsanfragen", paragraphs: ["Der Header Prüfer fasst SPF, DKIM, DMARC, Reply To und Versandweg zusammen. Auch bestandene Prüfungen beweisen nicht, dass eine konkrete Anfrage legitim ist.", "Bei Zahlungsanfragen sind Zeitdruck, geänderte Bankdaten, Geheimhaltung oder ungewöhnliche Zahlungsmittel Gründe für eine unabhängige Bestätigung über einen bereits bekannten Kontaktweg."] },
      { title: "Weiterleitungen und offizielle Links", paragraphs: ["Eine bekannte Weiterleitungskette kann lokal nach Domains, HTTPS und Anzahl der Stationen geordnet werden. Das Werkzeug folgt den Links nicht, sondern analysiert nur die eingefügten Adressen.", "Unternehmen können außerdem einen kurzen Hinweis zu ihrer offiziellen Domain erstellen. Ein klarer offizieller Kontaktweg hilft Kunden, unerwartete Nachrichten zu prüfen."] },
    ],
    faqs: [
      { question: "Wird das QR Bild hochgeladen?", answer: "Nein. Die Auswertung erfolgt lokal im Browser, sofern dieser die Funktion unterstützt. Das Ziel wird nicht automatisch geöffnet." },
      { question: "Beweist ein bestandener E Mail Check die Identität?", answer: "Nein. Header und Authentifizierung sind nur ein Teil der Prüfung. Kritische Anfragen sollten unabhängig bestätigt werden." },
      { question: "Kann Navines ein ähnliches Werkzeug für ein Unternehmen bauen?", answer: "Ja. Ausgangspunkt sind ein klarer Anwendungsfall, erlaubte Daten, verständliche Grenzen und ein sinnvoller nächster Schritt für Nutzer oder Mitarbeitende." },
    ],
    cta: { title: "Ein nützliches Werkzeug für Ihre Website planen", text: "Beschreiben Sie uns die wiederkehrende Frage oder Prüfung. Wir prüfen, ob daraus ein kleines, klares und verantwortungsvoll gebautes Werkzeug werden kann.", whatsappLabel: "Über WhatsApp sprechen", emailLabel: "E Mail senden" },
  },
  jp: {
    locale: "jp",
    slug: "local-safety-tools-qr-email-links",
    metaTitle: "QRコード、メールヘッダー、リンクを確認するローカルツール",
    metaDescription: "QRコード画像、メールヘッダー、支払い依頼、リダイレクト経路を確認できる20のローカルブラウザツールを実務目線で解説します。",
    title: "QRコード、メール、リンクを開く前に確認するための実務ツール",
    excerpt: "20のローカルツールが、リンクを自動で開いたり入力内容をサーバーへ送ったりせず、判断に必要な注意点を整理します。",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "Navinesチーム",
    sections: [
      { title: "小さな確認が必要な理由", paragraphs: ["デジタル上のトラブルは、印刷物のQRコード、返信先が異なるメール、急な振込依頼など、小さな違和感から始まることがあります。ローカルツールは、その違和感を整理して次の確認につなげます。", "結果は参考情報であり、安全性を保証するものではありません。重要な操作は、既に知っている公式窓口でも確認してください。"] },
      { title: "画像からQRコードを読み取る", paragraphs: ["QRスキャナーは画像をブラウザ内で読み取り、リンク先を自動で開かずにURLを表示します。移動する前にドメインを確認できることが重要です。", "印刷用QRチェックでは、HTTPS、モバイル画面、代替URL、コントラスト、実際の印刷物での読み取りまで確認します。"] },
      { title: "メールヘッダーと支払い依頼", paragraphs: ["メールヘッダー確認では、SPF、DKIM、DMARC、Reply To、配送経路を整理します。ただし、認証が成功していても依頼内容が正しいとは限りません。", "急かす表現、振込先変更、秘密保持、特殊な支払い方法がある場合は、同じメールに返信せず、既知の連絡先から担当者へ確認します。"] },
      { title: "リダイレクトと公式リンク", paragraphs: ["既に取得したリダイレクト経路を貼り付けると、ドメイン数、HTTPS、短縮URL、段階数を整理できます。ツール自体はリンクを開きません。", "公式ドメインと確認方法を明記した短い案内文も作成できます。顧客が迷わず確認できる情報は、日常の信頼づくりに役立ちます。"] },
    ],
    faqs: [
      { question: "QR画像はサーバーへ送信されますか？", answer: "いいえ。対応ブラウザでは端末内で処理され、リンク先も自動では開きません。" },
      { question: "メール認証が成功すれば安全ですか？", answer: "安全を保証するものではありません。重要な依頼は、既知の公式窓口から別途確認してください。" },
      { question: "自社向けの確認ツールも作れますか？", answer: "はい。利用目的、扱えるデータ、明確な制限、利用者にとっての次の行動を整理して設計します。" },
    ],
    cta: { title: "自社サイトに役立つツールを", text: "利用者が繰り返し困っている確認や作業を教えてください。小さく分かりやすいツールにできるか検討します。", whatsappLabel: "WhatsAppで相談", emailLabel: "メールで相談" },
  },
  ar: {
    locale: "ar",
    slug: "local-safety-tools-qr-email-links",
    metaTitle: "أدوات محلية لفحص QR وترويسات البريد والروابط",
    metaDescription: "دليل عملي إلى 20 أداة محلية لفحص صور QR وترويسات البريد وطلبات الدفع وسلاسل التحويل قبل اتخاذ إجراء رقمي.",
    title: "فحص رموز QR والبريد والروابط قبل أن تتحول الإشارة الصغيرة إلى مشكلة",
    excerpt: "20 أداة تعمل محلياً في المتصفح وتساعد على ترتيب إشارات الخطر من دون فتح الروابط تلقائياً أو إرسال المدخلات إلى خادم.",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "فريق نبي نس",
    sections: [
      { title: "لماذا يفيد الفحص القصير", paragraphs: ["قد يبدأ الخطر من تفصيل صغير مثل رمز QR مطبوع أو عنوان Reply To مختلف أو طلب دفع عاجل. تساعد الأداة المحلية على رؤية هذه العلامات وترتيب خطوة التحقق التالية.", "النتائج مؤشرات للمراجعة وليست ضماناً للأمان. القرارات الحساسة تحتاج أيضاً إلى تحقق عبر مصدر رسمي معروف مسبقاً."] },
      { title: "قراءة QR من صورة", paragraphs: ["يقرأ الماسح الرمز داخل المتصفح ويعرض عنوان الوجهة من دون فتحه تلقائياً. بذلك يمكن فحص النطاق قبل الانتقال إليه.", "قبل طباعة حملة QR من المهم أيضاً فحص تجربة الهاتف وHTTPS والرابط البديل والتباين والتجربة على نسخة مطبوعة حقيقية."] },
      { title: "ترويسات البريد وطلبات الدفع", paragraphs: ["تلخص أداة الترويسات SPF وDKIM وDMARC وReply To ومسار الرسالة. حتى نجاح هذه الفحوص لا يثبت أن الطلب نفسه مشروع.", "الاستعجال أو تغيير بيانات البنك أو طلب السرية أو وسيلة دفع غير معتادة أسباب كافية للتوقف والتأكد عبر قناة مستقلة معروفة."] },
      { title: "سلاسل التحويل والروابط الرسمية", paragraphs: ["يمكن ترتيب سلسلة تحويل معروفة حسب النطاقات وHTTPS وعدد الخطوات. الأداة لا تتبع الروابط بل تحلل العناوين التي أدخلها المستخدم فقط.", "كما يمكن للشركة إنشاء تنبيه قصير يوضح نطاقها الرسمي وطريقة التواصل الموثوقة، ليسهل على العملاء التحقق من الرسائل غير المتوقعة."] },
    ],
    faqs: [
      { question: "هل تُرفع صورة QR إلى الخادم؟", answer: "لا. تتم القراءة محلياً في المتصفح عندما تكون الميزة مدعومة، ولا تُفتح الوجهة تلقائياً." },
      { question: "هل نجاح SPF وDKIM وDMARC يثبت أن الرسالة آمنة؟", answer: "لا. هو جزء من الصورة فقط، ويجب تأكيد الطلبات الحساسة عبر قناة رسمية مستقلة." },
      { question: "هل يمكن بناء أداة مشابهة لموقع شركة؟", answer: "نعم. نبدأ بحاجة واضحة وبيانات مسموحة وحدود مفهومة وخطوة عملية مفيدة للمستخدم أو للفريق." },
    ],
    cta: { title: "خططوا لأداة مفيدة داخل موقعكم", text: "أخبرونا عن السؤال أو الفحص المتكرر لدى العملاء أو الفريق، وسنبحث إمكانية تحويله إلى أداة واضحة ومسؤولة.", whatsappLabel: "تحدثوا معنا عبر واتساب", emailLabel: "أرسلوا بريداً" },
  },
  hi: {
    locale: "hi",
    slug: "local-safety-tools-qr-email-links",
    metaTitle: "QR, ईमेल हेडर और लिंक जाँचने के स्थानीय टूल",
    metaDescription: "QR चित्र, ईमेल हेडर, भुगतान अनुरोध और रीडायरेक्ट क्रम जाँचने वाले 20 स्थानीय ब्राउज़र टूल का व्यावहारिक मार्गदर्शन।",
    title: "QR कोड, ईमेल और लिंक खोलने से पहले छोटी लेकिन उपयोगी जाँच",
    excerpt: "20 स्थानीय ब्राउज़र टूल बिना लिंक अपने आप खोले या इनपुट सर्वर पर भेजे, जरूरी संकेतों को समझने में मदद करते हैं।",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "नवीनेस टीम",
    sections: [
      { title: "छोटी जाँच क्यों जरूरी है", paragraphs: ["कई डिजिटल समस्याएँ एक छोटे संकेत से शुरू होती हैं, जैसे प्रिंट पर QR कोड, अलग Reply To पता या अचानक आया भुगतान अनुरोध। स्थानीय टूल इन संकेतों को व्यवस्थित करके अगली सही जाँच तय करने में मदद करता है।", "परिणाम केवल संकेत हैं, सुरक्षा की गारंटी नहीं। संवेदनशील कार्रवाई की पुष्टि किसी पहले से ज्ञात आधिकारिक स्रोत से भी करनी चाहिए।"] },
      { title: "चित्र से QR कोड पढ़ना", paragraphs: ["QR स्कैनर चित्र को ब्राउज़र में पढ़ता है और लक्ष्य को अपने आप खोले बिना URL दिखाता है। इससे आगे बढ़ने से पहले डोमेन देखा जा सकता है।", "प्रिंट अभियान के लिए मोबाइल अनुभव, HTTPS, वैकल्पिक URL, कंट्रास्ट और असली प्रिंट पर स्कैन परीक्षण भी जरूरी हैं।"] },
      { title: "ईमेल हेडर और भुगतान अनुरोध", paragraphs: ["ईमेल हेडर टूल SPF, DKIM, DMARC, Reply To और डिलीवरी मार्ग का सार देता है। सफल प्रमाणीकरण भी किसी खास अनुरोध की वैधता साबित नहीं करता।", "जल्दबाजी, बैंक विवरण बदलना, गोपनीयता पर जोर या असामान्य भुगतान तरीका हो तो परिचित आधिकारिक संपर्क से अलग पुष्टि करें।"] },
      { title: "रीडायरेक्ट और आधिकारिक लिंक", paragraphs: ["पहले से मिली रीडायरेक्ट सूची को डोमेन, HTTPS और चरणों के अनुसार जाँचा जा सकता है। टूल लिंक का पीछा नहीं करता।", "व्यवसाय अपने आधिकारिक डोमेन और सुरक्षित पुष्टि के तरीके का छोटा संदेश भी बना सकते हैं, ताकि ग्राहक अनपेक्षित संदेश पहचान सकें।"] },
    ],
    faqs: [
      { question: "क्या QR चित्र सर्वर पर भेजा जाता है?", answer: "नहीं। समर्थित ब्राउज़र में जाँच स्थानीय रहती है और लक्ष्य अपने आप नहीं खुलता।" },
      { question: "क्या ईमेल प्रमाणीकरण सफल होने पर संदेश सुरक्षित है?", answer: "यह गारंटी नहीं है। संवेदनशील अनुरोध की अलग आधिकारिक माध्यम से पुष्टि करनी चाहिए।" },
      { question: "क्या व्यवसाय के लिए ऐसा टूल बनाया जा सकता है?", answer: "हाँ। स्पष्ट उपयोग, अनुमत डेटा, समझने योग्य सीमाएँ और उपयोगकर्ता के अगले उपयोगी कदम के आधार पर टूल बनाया जा सकता है।" },
    ],
    cta: { title: "अपनी वेबसाइट के लिए उपयोगी टूल सोचें", text: "ग्राहकों या टीम की बार बार आने वाली जाँच बताइए। हम देखेंगे कि उसे छोटे, स्पष्ट और जिम्मेदार टूल में कैसे बदला जा सकता है।", whatsappLabel: "WhatsApp पर बात करें", emailLabel: "ईमेल भेजें" },
  },
  fr: {
    locale: "fr",
    slug: "outils-locaux-securite-qr-email-liens",
    metaTitle: "Outils locaux pour QR codes, en-têtes e-mail et liens",
    metaDescription: "Guide pratique de 20 outils locaux pour analyser QR codes, en-têtes e-mail, demandes de paiement, redirections et campagnes.",
    title: "Vérifier QR codes, e-mails et liens avant qu’un petit doute ne devienne un problème",
    excerpt: "20 outils locaux dans le navigateur structurent les signaux utiles sans ouvrir automatiquement les liens ni envoyer la saisie à un serveur.",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "Équipe Navines",
    sections: [
      { title: "Pourquoi une vérification courte est utile", paragraphs: ["Un incident peut commencer par un détail discret, comme un QR code imprimé, une adresse Reply To différente ou une demande de paiement urgente. Un outil local aide à rendre ces signaux visibles et à choisir la vérification suivante.", "Les résultats donnent des repères et non une garantie de sécurité. Toute action sensible doit aussi être confirmée par une source officielle déjà connue."] },
      { title: "Lire un QR code depuis une image", paragraphs: ["Le scanner lit le code dans le navigateur, affiche l’adresse et n’ouvre pas automatiquement la destination. On peut donc examiner le domaine avant de continuer.", "Pour une campagne imprimée, une checklist complète ce contrôle avec HTTPS, expérience mobile, URL de secours, contraste et test sur un véritable exemplaire imprimé."] },
      { title: "En-têtes e-mail et demandes de paiement", paragraphs: ["L’outil d’en-têtes résume SPF, DKIM, DMARC, Reply To et le parcours du message. Même des résultats valides ne prouvent pas qu’une demande précise est légitime.", "Une urgence, un changement de coordonnées bancaires, une demande de secret ou un moyen de paiement inhabituel justifient une confirmation indépendante par un contact connu."] },
      { title: "Redirections et liens officiels", paragraphs: ["Une chaîne de redirections déjà identifiée peut être classée par domaines, HTTPS et nombre d’étapes. L’outil ne suit pas les liens et analyse uniquement les adresses fournies.", "Une entreprise peut également préparer une courte notice indiquant son domaine officiel et son canal de vérification, afin d’aider les clients face aux messages inattendus."] },
    ],
    faqs: [
      { question: "L’image du QR code est-elle envoyée à un serveur ?", answer: "Non. Sur un navigateur compatible, la lecture reste locale et la destination ne s’ouvre pas automatiquement." },
      { question: "Un résultat SPF, DKIM et DMARC valide suffit-il ?", answer: "Non. Il faut confirmer séparément toute demande sensible par un canal officiel connu." },
      { question: "Navines peut-elle créer un outil similaire pour une entreprise ?", answer: "Oui. Nous partons d’un usage clair, de données autorisées, de limites explicites et d’une action réellement utile pour le public ou l’équipe." },
    ],
    cta: { title: "Concevoir un outil utile pour votre site", text: "Présentez-nous la question ou la vérification qui revient souvent. Nous étudierons une version courte, claire et responsable.", whatsappLabel: "Parler sur WhatsApp", emailLabel: "Envoyer un e-mail" },
  },
  zh: {
    locale: "zh",
    slug: "local-safety-tools-qr-email-links",
    metaTitle: "本地二维码、邮件头和链接检查工具",
    metaDescription: "介绍20项本地浏览器工具，用于检查二维码图片、邮件头、付款请求、重定向链和数字活动。",
    title: "在小问题变成风险之前检查二维码、邮件和链接",
    excerpt: "20项本地浏览器工具帮助整理风险信号，不会自动打开链接，也不会把输入内容发送到服务器。",
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-11",
    author: "Navines团队",
    sections: [
      { title: "为什么短暂检查很重要", paragraphs: ["很多数字风险从一个小细节开始，例如印刷品上的二维码、不同的Reply To地址或突然出现的付款请求。本地工具可以把这些信号整理出来，并帮助用户决定下一步如何核实。", "检查结果只是提示，不是安全保证。敏感操作还应通过之前已知的官方渠道单独确认。"] },
      { title: "从图片读取二维码", paragraphs: ["二维码扫描器在浏览器内读取图片，显示目标网址，但不会自动打开。用户可以在访问前先检查域名。", "印刷活动还应检查HTTPS、移动页面、备用网址、对比度，并使用真实印刷样品进行扫描测试。"] },
      { title: "邮件头和付款请求", paragraphs: ["邮件头工具会整理SPF、DKIM、DMARC、Reply To和邮件路径。即使验证通过，也不能证明某个具体请求一定真实。", "如果出现催促、银行信息变更、保密要求或异常付款方式，应通过已知官方联系方式单独确认。"] },
      { title: "重定向链和官方链接", paragraphs: ["已经获得的重定向链可以按域名、HTTPS和跳转次数进行检查。工具不会访问这些链接，只分析用户粘贴的地址。", "企业还可以生成一段官方域名说明，告诉客户如何核验意外收到的信息，减少日常沟通中的误解。"] },
    ],
    faqs: [
      { question: "二维码图片会上传到服务器吗？", answer: "不会。在支持该功能的浏览器中，读取过程保留在本地，目标网址也不会自动打开。" },
      { question: "邮件验证通过就代表安全吗？", answer: "不代表。敏感请求仍应通过已知的官方渠道单独核实。" },
      { question: "可以为企业开发类似工具吗？", answer: "可以。开发会围绕明确用途、允许使用的数据、清楚的限制和对用户真正有价值的下一步来设计。" },
    ],
    cta: { title: "为网站规划一个真正有用的工具", text: "告诉我们客户或团队经常重复的检查，我们会评估如何把它变成简洁、清楚并负责任的工具。", whatsappLabel: "通过WhatsApp联系", emailLabel: "发送邮件" },
  },
};
